### ISSUE TITLE
Error for input string: "@fraction/icon_viewport_size" in ic_panorama.xml file when building the project

### ISSUE THREAD

**Issue by israelmatavele** [googlesamples/android-OurStreets#3]
Information:Gradle tasks [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources]
D:\AndroidStudioProjects\OurStreets\app\src\main\res\drawable\ic_panorama.xml
      Error:Error: For input string: "@fraction/icon_viewport_size"
Error:Execution failed for task ':app:mergeDebugResources'.
> D:\AndroidStudioProjects\OurStreets\app\src\main\res\drawable\ic_panorama.xml: Error: For input string: "@fraction/icon_viewport_size"

**Comment by keyboardsurfer** [comment]
A fresh clone with `./gradlew assembleDebug` works fine.
Please add more info on how to reproduce this issue.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
